control:
   -  id: 1
      name: p8_enable
      pin_id: P9_42
      trigger: low
i2cs:
   -  id: A
      bus: I2C1
      addr: 0x20
      gpio_default: 0xff
   -  id: B
      bus: I2C1
      addr: 0x21
      gpio_default: 0xff
   -  id: C
      bus: I2C1
      addr: 0x22
      gpio_default: 0xff
   -  id: D
      bus: I2C1
      addr: 0x24
      gpio_default: 0xff
valves:
   -  id: 1
      name: Decant
      type: powered
      open: I.C.2
      activate: I.C.3
      sense_closed: P9_12
      sense_open: P9_11
      trigger: low
   -  id: 2
      name: Bright Out
      type: powered
      open: I.C.4
      activate: I.C.5
      sense_open: P9_13
      sense_closed: P9_14
      trigger: low
   -  id: 3
      name: Bright In
      type: powered
      open: I.C.6
      activate: I.C.7
      sense_open: P9_17
      sense_closed: P9_18
      trigger: low
   -  id: 4
      name: Filter purge Out
      type: powered
      open: I.A.0
      activate: I.A.1
      sense_open: P9_21
      sense_closed: P9_22
      trigger: low
   -  id: 5
      name: Brew Out
      type: powered
      open: I.A.2
      activate: I.A.3
      sense_open: P9_23
      sense_closed: P9_24
      trigger: low
   -  id: 6
      name: Brew In
      type: powered
      open: I.A.4
      activate: I.A.5
      sense_open: P9_25
      sense_closed: P9_26
      trigger: low
   -  id: 7
      name: Brew Vacuum
      type: powered
      open: I.A.6
      activate: I.A.7
      sense_open: P9_27
      sense_closed: P9_28
      trigger: low
   -  id: 8
      name: Filter H2O
      type: NC
      open: I.D.0
      trigger: low
   -  id: 9
      name: Filter Backflush
      type: NC
      open: I.D.1
      trigger: low
   -  id: 10
      name: Brew H2O
      type: NC
      open: I.D.2
      trigger: low
   -  id: 11
      name: process H2O
      type: NC
      open: I.D.3
      trigger: low
   -  id: 12
      name: Brew N2
      type: NC
      open: I.D.4
      trigger: low
   -  id: 13
      name: Bright N2
      type: NC
      open: I.D.5
      trigger: low
   -  id: 14
      name: Condition N2
      type: NC
      open: I.D.6
      trigger: low
   -  id: 15
      name: Circulator
      type: NC
      open: I.C.0
      trigger: low
   -  id: 16
      name: Vacuum Pump
      type: NC
      open: I.C.1
      trigger: low
switches:
   -  id: 1
      name: clean
      pin_id: P9_29
      pull_down: yes
   -  id: 2
      name: brew
      pin_id: P9_30
      pull_down: yes
   -  id: 3
      name: run
      pin_id: P9_31
      pull_down: yes
      duplicate: true
   -  id: 4
      name: halt
      pin_id: P9_31
      pull_down: yes
      duplicate: true
lights:
   -  name: done
      pin_id: P8_19
   -  name: brew
      pin_id: P8_26
   -  name: clean
      pin_id: P8_27
   -  name: load
      pin_id: P8_28
   -  name: ready
      pin_id: P8_29
   -  name: run
      pin_id: P8_30
