control:
   -  id: 1
      name: p8_enable
      pin_id: P9_42
      trigger: low
i2cs:
   -  id: A
      bus: I2C1
      addr: 0x20
   -  id: B
      bus: I2C1
      addr: 0x21
   -  id: C
      bus: I2C1
      addr: 0x23
   -  id: D
      bus: I2C1
      addr: 0x24
valves:
   -  id: 1
      name: Decant
      type: powered
      open: P8_35
      close: P8_36
      sense_closed: P9_27
      sense_open: P9_28
      trigger: low
   -  id: 2
      name: Bright Out
      type: powered
      open: P8_33
      close: P8_34
      sense_open: P9_25
      sense_closed: P9_26
      trigger: low
   -  id: 8
      name: Filter H2O
      type: NC
      open: P8_39
      trigger: high
   -  id: 9
      name: Filter Backflush
      type: NC
      open: P8_40
      trigger: high
switches:
   -  id: 1
      name: clean
      pin_id: P9_29
      pull_down: yes
   -  id: 2
      name: brew
      pin_id: P9_30
      pull_down: yes
   -  id: 3
      name: run
      pin_id: P9_31
      pull_down: yes
   -  id: 4
      name: halt
      pin_id: P9_31
      pull_down: yes
lights:
   -  name: done
      pin_id: P8_19
   -  name: brew
      pin_id: P8_26
   -  name: clean
      pin_id: P8_27
   -  name: load
      pin_id: P8_28
   -  name: ready
      pin_id: P8_29
   -  name: run
      pin_id: P8_30
